#!/usr/bin/env python
# The command-line interface for secure GGGolf
# (C) Copyright 2018-2019 Yu-Yueh Liu

"""Secure GG Golf Client

Usage:
  ./gggolfclient [option] <location name>
  ./gggolfclient -r cerf
  ./gggolfclient (-h | --help)
  ./gggolfclient --version

Options:
  -h --help     Show this screen.
  --version     Show version.
  -r --reg      Register 

"""
from docopt import docopt


if __name__ == '__main__':
    arguments = docopt(__doc__, version='GGGolf 1.0')
    print(arguments)